#!/bin/bash

# NOTE: this file (and 'excel') use relative paths. Make sure to 
# run this script from origins_generators/generators/excel/.

# Generate new output and compare it with the expected output file. 
# A diff will not work because the facts may not be generated in 
# the same order each time. (generator uses dictionaries)
rm -f testing/test_output.csv
./excel testing/test_input.xlsx test >> testing/test_output.csv
./testing/compare_test_output.py
